#!/bin/sh

### BEGIN INIT INFO
# Provides:          webtoink
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the WebToInk application
# Description:       starts WebToInk using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/home/tlorenz/.cabal/bin

DAEMON=/home/tlorenz/.cabal/bin/WebToInk
DAEMON_OPTS=Production

NAME=webtoink
DESC=webtoink

START_FOLDER=/home/tlorenz/dev/haskell/webtoink/webtoink
PIDFILE=/var/run/$NAME.pid 


. /lib/lsb/init-functions

start() {
    echo -n "Starting $DESC: "
    start-stop-daemon --start --background --quiet --make-pidfile \
                      --pidfile $PIDFILE \
                      --chdir $START_FOLDER \
                      --exec $DAEMON -- $DAEMON_OPTS
    echo "."
}

stop() {
    echo -n "Stopping $DESC: "
    start-stop-daemon --stop --quiet \
                      --pidfile $PIDFILE \
                      --exec $DAEMON
    echo "."
}

status() {
    status_of_proc -p $PIDFILE "$DAEMON" webtoink && exit 0 || exit $?
}


case "$1" in
	start)
	    start
		;;

	stop)
	    stop
		;;

	restart|force-reload)
		echo -n "Restarting $DESC ...\n"
		stop
		start
		;;

	status)
		status
		;;
	*)
		echo "Usage: $NAME {start|stop|restart|status}" >&2
		exit 1
		;;
esac

exit 0
